import { CommonModule } from '@angular/common';
import {
    Component,
    computed,
    effect,
    EventEmitter,
    HostBinding,
    input,
    Input,
    InputSignal,
    OnInit,
    Output,
    Signal,
    signal,
    untracked,
    viewChild,
    WritableSignal,
    inject,
} from '@angular/core';
import { HOME_REPOSITORY, Node } from 'ngx-edu-sharing-api';
import { ImagesResponse } from 'ngx-edu-sharing-b-api';
import { EduSharingUiCommonModule, OptionItem } from 'ngx-edu-sharing-ui';
import { v4 as uuidv4 } from 'uuid';
import { Closable } from '../../../../../features/dialogs/card-dialog/card-dialog-config';
import { YES_OR_NO } from '../../../../../features/dialogs/dialog-modules/generic-dialog/generic-dialog-data';
import { DialogsService } from '../../../../../features/dialogs/dialogs.service';
import { MdsEditorWidgetPreviewComponent } from '../../../../../features/mds/mds-editor/widgets/mds-editor-widget-preview/mds-editor-widget-preview.component';
import { MdsModule } from '../../../../../features/mds/mds.module';
import { AiHelperService } from '../../../shared/services/ai-helper.service';
import { TopicPageHelperService } from '../../../shared/services/topic-page-helper.service';
import { AiLabelComponent } from '../ai-label/ai-label.component';

/**
 * Topic page image that is either AI generated, uploaded by the user or taken from a fallback
 * node. The standalone preview widget displays it and offers the edit and delete controls; this
 * component adds AI generation to its menu and persists the result as a child of the widget node.
 */
@Component({
    selector: 'es-image-wrapper',
    imports: [AiLabelComponent, CommonModule, EduSharingUiCommonModule, MdsModule],
    templateUrl: './image-wrapper.component.html',
    styleUrls: ['./image-wrapper.component.scss'],
})
export class ImageWrapperComponent implements OnInit {
    private aiHelperService = inject(AiHelperService);
    private dialogsService = inject(DialogsService);
    private topicPageHelperService = inject(TopicPageHelperService);

    // CONSTANTS
    private readonly AI_IMAGE_MIMETYPE: string = 'image/jpeg';
    protected readonly i18nPrefix: string = 'TOPIC_PAGE.WIDGET.IMAGE_WRAPPER.';
    private readonly UPLOAD_PREFIX: string = 'UPLOAD_';

    // inputs relevant for public AI generation (specifies the node, in which the prompt is stored, and its context, which is part of this prompt)
    // those can be unset, if the image should not be generated by AI
    contextNodeId: InputSignal<string> = input<string>(null);
    widgetNodeId: InputSignal<string> = input<string>(null);
    // optional fallback node for showing a preview, if no image was uploaded or generated
    @Input() fallbackNode?: Node;
    @HostBinding('style.--mobile-max-height') @Input() mobileMaxHeight?: string = '350px';
    @HostBinding('class.edit-mode') @Input() editMode?: boolean = false;
    supportAiGeneration: InputSignal<boolean> = input(false);
    supportUserUpload: InputSignal<boolean> = input(true);
    // computed values to check for valid inputs
    aiGenerationSupportedAndValid: Signal<boolean> = computed((): boolean => {
        return (
            this.supportAiGeneration() &&
            this.contextNodeId() !== null &&
            this.widgetNodeId() !== null
        );
    });
    userUploadSupportedAndValid: Signal<boolean> = computed((): boolean => {
        return this.supportUserUpload() && this.uploadParentNodeId() !== null;
    });
    atLeastOneEditOptionSupported: Signal<boolean> = computed((): boolean => {
        return this.aiGenerationSupportedAndValid() || this.userUploadSupportedAndValid();
    });
    // by default, the image should be generated by AI
    aiGeneratedImage: InputSignal<boolean> = input<boolean>(true);
    userUploadedNodeId: InputSignal<string> = input<string>(null);
    uploadParentNodeId: InputSignal<string> = input<string>(null);
    // outputs to persist the config or change the image variables
    @Output() aiGeneratedImageChange: EventEmitter<boolean> = new EventEmitter<boolean>();
    @Output() userUploadedNodeIdChange: EventEmitter<string> = new EventEmitter<string>();
    @Output() persistConfig: EventEmitter<boolean> = new EventEmitter<boolean>();

    deleteImageDisabled: Signal<boolean> = computed((): boolean => {
        return !this.aiGeneratedImage() && !this.userUploadedNodeId();
    });
    // (re)generating the AI image is offered in the preview widget's change menu
    aiOptions: Signal<OptionItem[]> = computed((): OptionItem[] => {
        if (!this.aiGenerationSupportedAndValid()) {
            return [];
        }
        const regenerate: boolean = this.aiGeneratedImage() && !this.userUploadedNodeId();
        return [
            new OptionItem(
                this.i18nPrefix + (regenerate ? 'REGENERATE' : 'GENERATE'),
                'magic_button',
                () => void this.generateImage(),
            ),
        ];
    });
    private previewWidget: Signal<MdsEditorWidgetPreviewComponent> = viewChild(
        MdsEditorWidgetPreviewComponent,
    );
    // the node whose preview is shown; AI images are wrapped into a node carrying inline data
    imageNode: WritableSignal<Node> = signal(null);
    // last uploaded node id that was loaded, to avoid fetching the same image twice
    private lastLoadedUploadId: string | null = null;
    imageProcessing: WritableSignal<boolean> = signal(false);
    initialized: WritableSignal<boolean> = signal(false);

    constructor() {
        // listen to changes of the input variables (ensures that the image is created as a child of the widget node)
        effect((): void => {
            const parentId = this.uploadParentNodeId();
            if (parentId) {
                this.imageProcessing.set(true);
                void this.handleUploadBlob();
            }
        });
        // (re)load the uploaded image whenever its node id changes after init — the parent may set
        // userUploadedNodeId after this component was created (e.g. when switching to a page
        // template), and loadImage in ngOnInit only runs once. Guarded by lastLoadedUploadId so the
        // same id is never fetched twice (e.g. right after the ngOnInit load). Only the uploaded
        // branch runs here (a plain getNode, no AI generation); aiGeneratedImage is read untracked.
        effect((): void => {
            const uploadedNodeId = this.userUploadedNodeId();
            if (
                this.initialized() &&
                uploadedNodeId &&
                uploadedNodeId !== this.lastLoadedUploadId
            ) {
                this.lastLoadedUploadId = uploadedNodeId;
                void this.loadImage(
                    untracked(() => this.aiGeneratedImage()),
                    uploadedNodeId,
                );
            }
        });
    }

    /**
     * Initializes the component by loading the image based on the variables input
     * and setting the image processing to true during processing.
     */
    async ngOnInit(): Promise<void> {
        // set the image processing to true
        this.imageProcessing.set(true);
        // loads the image based on the variables set for aiGeneratedImage and userUploadedNodeId
        await this.loadImage(this.aiGeneratedImage(), this.userUploadedNodeId());
        // reset the image processing
        this.imageProcessing.set(false);
        // set the component to be initialized
        this.initialized.set(true);
    }

    /**
     * Loads an image based on the variables set for aiGeneratedImage and userUploadedNodeId.
     *
     * @param aiGeneratedImage
     * @param userUploadedNodeId
     * @param regenerateNecessary
     */
    async loadImage(
        aiGeneratedImage: boolean,
        userUploadedNodeId: string,
        regenerateNecessary: boolean = false,
    ): Promise<void> {
        // user has uploaded a custom image
        if (userUploadedNodeId) {
            // remember the loaded id so the reactive effect does not fetch it again
            this.lastLoadedUploadId = userUploadedNodeId;
            // an unavailable upload falls back to the fallback node below
            const uploadedNode: Node | null = await this.topicPageHelperService.getNodeIfAvailable(
                userUploadedNodeId,
            );
            if (uploadedNode?.preview?.url) {
                // the thumbnail of a fresh upload may still be pending (icon preview), but its
                // preview url serves the uploaded image either way
                this.showImageNode({
                    ...uploadedNode,
                    preview: { ...uploadedNode.preview, isIcon: false },
                });
                return;
            }
        } else if (aiGeneratedImage) {
            // user has selected an AI generated image
            try {
                const imageData: ImagesResponse = regenerateNecessary
                    ? await this.aiHelperService.updateAiImage(
                          this.widgetNodeId(),
                          this.contextNodeId(),
                      )
                    : await this.aiHelperService.createAiImage(
                          this.widgetNodeId(),
                          this.contextNodeId(),
                      );
                this.showImageNode(this.toInlineImageNode(imageData.data[0].b64_json));
                return;
            } catch (error) {
                console.error(error);
            }
        }
        // no own image available: fall back to the preview of the fallback node,
        // unless that preview is only the generic type icon
        if (this.fallbackNode?.preview && !this.fallbackNode.preview.isIcon) {
            this.showImageNode(this.fallbackNode);
            return;
        }
        this.showImageNode(null);
    }

    /**
     * Shows the given node and drops any change still pending in the preview widget.
     */
    private showImageNode(node: Node | null): void {
        this.imageNode.set(node);
        this.previewWidget()?.showStandaloneNode(node);
    }

    /**
     * Wraps a base64 encoded image into a node, so it can be shown like any node preview.
     */
    private toInlineImageNode(base64: string): Node {
        return {
            ref: { id: this.widgetNodeId(), repo: HOME_REPOSITORY },
            preview: { data: base64, mimetype: this.AI_IMAGE_MIMETYPE, isIcon: false },
        } as unknown as Node;
    }

    /**
     * Handles a change requested in the preview widget (picked image or delete request).
     */
    onPreviewChange(change: { file: File | null; delete: boolean }): void {
        if (this.imageProcessing()) {
            return;
        }
        // the widget offers picking an image even if only AI generation is supported
        if (change.file && this.userUploadSupportedAndValid()) {
            void this.imageChanged(change.file);
        } else if (change.delete) {
            void this.deleteImage();
        }
    }

    /**
     * Triggers the process of generating an AI image.
     */
    async generateImage(): Promise<void> {
        // set the image processing to true
        this.imageProcessing.set(true);
        // check, whether an AI generated image is already shown and a regeneration is requested
        const regenerateNecessary: boolean = this.aiGeneratedImage() && !this.userUploadedNodeId();
        // check, whether persisting is necessary
        const persistingNecessary: boolean =
            !this.aiGeneratedImage() || this.userUploadedNodeId() !== null;
        // update the variables for AI generated and delete a potentially existing user uploaded image
        if (!this.aiGeneratedImage()) {
            this.aiGeneratedImageChange.emit(true);
        }
        await this.deletePotentialUploadAndEmitValue();
        // persist the config
        if (persistingNecessary) {
            this.persistConfig.emit(true);
        }
        // emitted values are not updated synchronously, so input the emitted values here
        await this.loadImage(true, null, regenerateNecessary);
        // reset the image processing
        this.imageProcessing.set(false);
    }

    /**
     * Handles the deletion of an AI generated or a user uploaded image.
     */
    async deleteImage(): Promise<void> {
        // set the image processing to true
        this.imageProcessing.set(true);
        // reset both existing variables for AI generated or user uploaded image (delete potentially existing user uploaded image)
        if (this.aiGeneratedImage()) {
            this.aiGeneratedImageChange.emit(false);
        }
        await this.deletePotentialUploadAndEmitValue();
        // persist the config
        this.persistConfig.emit(true);
        // load the image depending on the currently selected mode
        await this.loadImage(false, null);
        // reset the image processing
        this.imageProcessing.set(false);
    }

    /**
     * Handles the upload of an image if the user confirms that he/she has the necessary rights.
     *
     * @param file
     */
    async imageChanged(file: File): Promise<void> {
        const dialogRef = await this.dialogsService.openGenericDialog({
            title: this.i18nPrefix + 'UPLOAD',
            message: this.i18nPrefix + 'IMAGE_UPLOAD_CONFIRMATION_TEXT',
            buttons: YES_OR_NO,
            closable: Closable.Casual,
        });
        dialogRef.afterClosed().subscribe(async (response) => {
            if (response !== 'YES') {
                return;
            }
            // set the image processing to true
            this.imageProcessing.set(true);
            // delete a potentially existing user uploaded image
            await this.deletePotentialUploadAndEmitValue();
            // upload the new image
            this.topicPageHelperService.setBlobToUpload(new Blob([file], { type: file.type }));
            if (!this.uploadParentNodeId()) {
                // persist the config before handling the actual upload to ensure
                // that the image is created as a child of the widget node
                this.persistConfig.emit(true);
            } else {
                await this.handleUploadBlob();
            }
        });
    }

    /**
     * Handles the actual upload of the blob.
     */
    async handleUploadBlob(): Promise<void> {
        if (!this.topicPageHelperService.getBlobToUpload()) {
            // reset the image processing
            this.imageProcessing.set(false);
            return;
        }
        const imageNode: Node = await this.topicPageHelperService.uploadFile(
            this.uploadParentNodeId(),
            this.UPLOAD_PREFIX + uuidv4(),
            this.topicPageHelperService.getBlobToUpload().type,
            this.topicPageHelperService.getBlobToUpload(),
        );
        // reset the blob
        this.topicPageHelperService.setBlobToUpload(null);
        // update the variable of the user uploaded image
        this.userUploadedNodeIdChange.emit(imageNode.ref.id);
        // persist the config
        this.persistConfig.emit(true);
        // load the image depending on the currently selected mode
        await this.loadImage(this.aiGeneratedImage(), imageNode.ref.id);
        // reset the image processing
        this.imageProcessing.set(false);
    }

    /**
     * Helper function to delete a potentially existing user uploaded image.
     */
    async deletePotentialUploadAndEmitValue(): Promise<void> {
        if (this.userUploadedNodeId()) {
            await this.topicPageHelperService.deleteNodeIfExists(this.userUploadedNodeId());
            this.userUploadedNodeIdChange.emit(null);
        }
    }
}
