import { CommonModule } from '@angular/common';
import {
    Component,
    computed,
    effect,
    EventEmitter,
    HostBinding,
    input,
    Input,
    InputSignal,
    OnInit,
    Output,
    Signal,
    signal,
    WritableSignal,
} from '@angular/core';
import { MatIconButton } from '@angular/material/button';
import { MatTooltip } from '@angular/material/tooltip';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { TranslateModule } from '@ngx-translate/core';
import { Node } from 'ngx-edu-sharing-api';
import { ImagesResponse } from 'ngx-edu-sharing-b-api';
import { EduSharingUiCommonModule } from 'ngx-edu-sharing-ui';
import { v4 as uuidv4 } from 'uuid';
import { Closable } from '../../../../../features/dialogs/card-dialog/card-dialog-config';
import { YES_OR_NO } from '../../../../../features/dialogs/dialog-modules/generic-dialog/generic-dialog-data';
import { DialogsService } from '../../../../../features/dialogs/dialogs.service';
import { TooltipAriaLabelDirective } from '../../../shared/directives/tooltip-aria-label.directive';
import { AiHelperService } from '../../../shared/services/ai-helper.service';
import { TopicPageHelperService } from '../../../shared/services/topic-page-helper.service';
import { AiLabelComponent } from '../ai-label/ai-label.component';

@Component({
    selector: 'es-image-wrapper',
    imports: [
        AiLabelComponent,
        CommonModule,
        EduSharingUiCommonModule,
        MatIconButton,
        MatTooltip,
        TooltipAriaLabelDirective,
        TranslateModule,
    ],
    templateUrl: './image-wrapper.component.html',
    styleUrls: ['./image-wrapper.component.scss'],
})
export class ImageWrapperComponent implements OnInit {
    // CONSTANTS
    private readonly BASE_64_PREFIX: string = 'data:image/jpg;base64,';
    protected readonly i18nPrefix: string = 'TOPIC_PAGE.WIDGET.IMAGE_WRAPPER.';
    private readonly UPLOAD_PREFIX: string = 'UPLOAD_';

    // inputs relevant for public AI generation (specifies the node, in which the prompt is stored, and its context, which is part of this prompt)
    // those can be unset, if the image should not be generated by AI
    contextNodeId: InputSignal<string> = input<string>(null);
    widgetNodeId: InputSignal<string> = input<string>(null);
    // optional fallback node for showing a preview, if no image was uploaded or generated
    @Input() fallbackNode?: Node;
    @HostBinding('style.--mobile-max-height') @Input() mobileMaxHeight?: string = '350px';
    @HostBinding('class.edit-mode') @Input() editMode?: boolean = false;
    supportAiGeneration: InputSignal<boolean> = input(false);
    supportUserUpload: InputSignal<boolean> = input(true);
    // computed values to check for valid inputs
    aiGenerationSupportedAndValid: Signal<boolean> = computed((): boolean => {
        return (
            this.supportAiGeneration() &&
            this.contextNodeId() !== null &&
            this.widgetNodeId() !== null
        );
    });
    userUploadSupportedAndValid: Signal<boolean> = computed((): boolean => {
        return this.supportUserUpload() && this.uploadParentNodeId() !== null;
    });
    atLeastOneEditOptionSupported: Signal<boolean> = computed((): boolean => {
        return this.aiGenerationSupportedAndValid() || this.userUploadSupportedAndValid();
    });
    // by default, the image should be generated by AI
    aiGeneratedImage: InputSignal<boolean> = input<boolean>(true);
    userUploadedNodeId: InputSignal<string> = input<string>(null);
    uploadParentNodeId: InputSignal<string> = input<string>(null);
    // outputs to persist the config or change the image variables
    @Output() aiGeneratedImageChange: EventEmitter<boolean> = new EventEmitter<boolean>();
    @Output() userUploadedNodeIdChange: EventEmitter<string> = new EventEmitter<string>();
    @Output() persistConfig: EventEmitter<boolean> = new EventEmitter<boolean>();

    deleteImageDisabled: Signal<boolean> = computed((): boolean => {
        return !this.aiGeneratedImage() && !this.userUploadedNodeId();
    });
    private fileInput: HTMLInputElement;
    imagePath: SafeResourceUrl;
    imageNode: Node;
    imageProcessing: WritableSignal<boolean> = signal(false);
    initialized: WritableSignal<boolean> = signal(false);

    constructor(
        private aiHelperService: AiHelperService,
        private dialogsService: DialogsService,
        private sanitizer: DomSanitizer,
        private topicPageHelperService: TopicPageHelperService,
    ) {
        // listen to changes of the input variables (ensures that the image is created as a child of the widget node)
        effect((): void => {
            const parentId = this.uploadParentNodeId();
            if (parentId) {
                this.imageProcessing.set(true);
                void this.handleUploadBlob();
            }
        });
    }

    /**
     * Initializes the component by loading the image based on the variables input
     * and setting the image processing to true during processing.
     */
    async ngOnInit(): Promise<void> {
        // set the image processing to true
        this.imageProcessing.set(true);
        // loads the image based on the variables set for aiGeneratedImage and userUploadedNodeId
        await this.loadImage(this.aiGeneratedImage(), this.userUploadedNodeId());
        // reset the image processing
        this.imageProcessing.set(false);
        // set the component to be initialized
        this.initialized.set(true);
    }

    /**
     * Loads an image based on the variables set for aiGeneratedImage and userUploadedNodeId.
     *
     * @param aiGeneratedImage
     * @param userUploadedNodeId
     * @param regenerateNecessary
     */
    async loadImage(
        aiGeneratedImage: boolean,
        userUploadedNodeId: string,
        regenerateNecessary: boolean = false,
    ): Promise<void> {
        const resetSources = () => {
            this.imagePath = null;
            this.imageNode = null;
        };
        // user has uploaded a custom image
        if (userUploadedNodeId) {
            const uploadedNode: Node = await this.topicPageHelperService.getNode(
                userUploadedNodeId,
            );
            if (uploadedNode.preview?.url) {
                // reset both sources before loading the new one
                resetSources();
                this.imageNode = uploadedNode;
            }
            return;
        }
        // user has selected an AI generated image
        if (aiGeneratedImage) {
            try {
                const imageData: ImagesResponse = regenerateNecessary
                    ? await this.aiHelperService.updateAiImage(
                          this.widgetNodeId(),
                          this.contextNodeId(),
                      )
                    : await this.aiHelperService.createAiImage(
                          this.widgetNodeId(),
                          this.contextNodeId(),
                      );
                // reset both sources before loading the new one
                resetSources();
                this.imagePath = this.sanitizer.bypassSecurityTrustResourceUrl(
                    this.BASE_64_PREFIX + imageData.data[0].b64_json,
                );
                return;
            } catch (error) {
                console.error(error);
            }
        }
        // neither option is true or the user has explicitly deleted the image and wants to reset to the image of the fallback node
        if (this.fallbackNode?.preview && !this.fallbackNode.preview.isIcon) {
            // reset both sources before loading the new one
            resetSources();
            this.imageNode = this.fallbackNode;
        }
        // reset both sources, if no condition matches
        resetSources();
    }

    /**
     * Triggers the process of generating an AI image when the related button is clicked.
     */
    async generateImage(): Promise<void> {
        // set the image processing to true
        this.imageProcessing.set(true);
        // check, whether an AI generated image is already shown and a regeneration is requested
        const regenerateNecessary: boolean = this.aiGeneratedImage() && !this.userUploadedNodeId();
        // check, whether persisting is necessary
        const persistingNecessary: boolean =
            !this.aiGeneratedImage() || this.userUploadedNodeId() !== null;
        // update the variables for AI generated and delete a potentially existing user uploaded image
        if (!this.aiGeneratedImage()) {
            this.aiGeneratedImageChange.emit(true);
        }
        await this.deletePotentialUploadAndEmitValue();
        // persist the config
        if (persistingNecessary) {
            this.persistConfig.emit(true);
        }
        // emitted values are not updated synchronously, so input the emitted values here
        await this.loadImage(true, null, regenerateNecessary);
        // reset the image processing
        this.imageProcessing.set(false);
    }

    /**
     * Handles the deletion of an AI generated or a user uploaded image.
     */
    async deleteImage(): Promise<void> {
        // set the image processing to true
        this.imageProcessing.set(true);
        // reset both existing variables for AI generated or user uploaded image (delete potentially existing user uploaded image)
        if (this.aiGeneratedImage()) {
            this.aiGeneratedImageChange.emit(false);
        }
        await this.deletePotentialUploadAndEmitValue();
        // persist the config
        this.persistConfig.emit(true);
        // load the image depending on the currently selected mode
        await this.loadImage(false, null);
        // reset the image processing
        this.imageProcessing.set(false);
    }

    /**
     * Triggers the file selection by simulating a click event on a given file input element.
     *
     * @param fileInput
     */
    uploadImageClicked(fileInput: HTMLInputElement): void {
        fileInput.click();
        // temporary save the file input element to be able to reset it later
        this.fileInput = fileInput;
    }

    /**
     * Handles the upload of an image if the user confirms that he/she has the necessary rights.
     *
     * @param event
     */
    async imageChanged(event: any): Promise<void> {
        if (!event.target.files || !event.target.files[0]) {
            return;
        }
        const dialogRef = await this.dialogsService.openGenericDialog({
            title: this.i18nPrefix + 'UPLOAD',
            message: this.i18nPrefix + 'IMAGE_UPLOAD_CONFIRMATION_TEXT',
            buttons: YES_OR_NO,
            closable: Closable.Casual,
        });
        dialogRef.afterClosed().subscribe(async (response) => {
            if (response === 'YES') {
                // set the image processing to true
                this.imageProcessing.set(true);
                // delete a potentially existing user uploaded image
                await this.deletePotentialUploadAndEmitValue();
                // upload the new image
                const uploadImage = event.target.files[0];
                const blob: Blob = new Blob([uploadImage], { type: uploadImage.type });
                this.topicPageHelperService.setBlobToUpload(blob);
                if (!this.uploadParentNodeId()) {
                    // persist the config before handling the actual upload to ensure
                    // that the image is created as a child of the widget node
                    this.persistConfig.emit(true);
                } else {
                    await this.handleUploadBlob();
                }
            }
        });
    }

    /**
     * Handles the actual upload of the blob.
     */
    async handleUploadBlob(): Promise<void> {
        if (!this.topicPageHelperService.getBlobToUpload()) {
            // reset the image processing
            this.imageProcessing.set(false);
            return;
        }
        const imageNode: Node = await this.topicPageHelperService.uploadFile(
            this.uploadParentNodeId(),
            this.UPLOAD_PREFIX + uuidv4(),
            this.topicPageHelperService.getBlobToUpload().type,
            this.topicPageHelperService.getBlobToUpload(),
        );
        // reset the blob
        this.topicPageHelperService.setBlobToUpload(null);
        // update the variable of the user uploaded image
        this.userUploadedNodeIdChange.emit(imageNode.ref.id);
        // persist the config
        this.persistConfig.emit(true);
        // load the image depending on the currently selected mode
        await this.loadImage(this.aiGeneratedImage(), imageNode.ref.id);
        // reset the file input
        if (this.fileInput) {
            this.fileInput.value = null;
        }
        // reset the image processing
        this.imageProcessing.set(false);
    }

    /**
     * Helper function to delete a potentially existing user uploaded image.
     */
    async deletePotentialUploadAndEmitValue(): Promise<void> {
        if (this.userUploadedNodeId()) {
            await this.topicPageHelperService.deleteNode(this.userUploadedNodeId());
            this.userUploadedNodeIdChange.emit(null);
        }
    }
}
