package org.edu_sharing.service.tracking;

public enum ActivityOnNodeEventType {
    DOWNLOAD_MATERIAL,
    OPEN_EXTERNAL_LINK, // open link in new tab was choosen
    VIEW_MATERIAL,
    VIEW_COLLECTION,
    VIEW_MATERIAL_EMBEDDED,
    VIEW_MATERIAL_PLAY_MEDIA, // When a video or audio file is actually started playing

    EDIT_MATERIAL,
    CHANGE_MATERIAL_OWNER,
    CREATE_MATERIAL,
    DELETE_MATERIAL,
    MOVE_MATERIAL,
    COPY_MATERIAL,
    FORK_MATERIAL,
    COMMENT_MATERIAL,
    REVERT_MATERIAL_VERSION,
    RATE_MATERIAL,
    UNRATE_MATERIAL,
    SHARE_MATERIAL,
    FEEDBACK_MATERIAL,
    UNSHARE_MATERIAL,
    CHANGE_MATERIAL_CONTENT,
    REPORT_MATERIAL,
    EDIT_MATERIAL_RELATION,
}
