package org.edu_sharing.service.tracking;

public enum ActivityOnNodeEventType {
    DOWNLOAD_MATERIAL,
    OPEN_EXTERNAL_LINK, // open link in new tab was choosen
    VIEW_MATERIAL,
    VIEW_COLLECTION,
    VIEW_MATERIAL_EMBEDDED,
    VIEW_MATERIAL_PLAY_MEDIA, // When a video or audio file is actually started playing

    // used in interceptors
    EDIT_MATERIAL,
    CREATE_MATERIAL,
    ARCHIVE_MATERIAL,
    DELETE_MATERIAL,
    MOVE_MATERIAL,
    COPY_MATERIAL,
    REVERT_MATERIAL_VERSION,
    CHANGE_MATERIAL_CONTENT,

    // used in endpoints or services
    CHANGE_MATERIAL_OWNER,
    FORK_MATERIAL,
    COMMENT_MATERIAL,
    RATE_MATERIAL,
    UNRATE_MATERIAL,
    LINK_SHARE_MATERIAL,
    LINK_UNSHARE_MATERIAL,
    FEEDBACK_MATERIAL,
    REPORT_MATERIAL,
    EDIT_MATERIAL_RELATION,
    PROPOSE_MATERIAL_TO_COLLECTION,
    WORKFLOW_CHANGED_ON_MATERIAL,
    ADD_MATERIAL_TO_COLLECTION
}
