namespace.prefix.cclom=http://www.campuscontent.de/model/lom/1.0
namespace.prefix.ccm=http://www.campuscontent.de/model/1.0

title=cclom:title
license=ccm:commonlicense_key
licenseVersion=ccm:commonlicense_cc_version

author=ccm:lifecyclecontributer_author
authorEditor=ccm:lifecyclecontributer_editor