package org.edu_sharing.service.suggestion;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Type of the suggestion")
public enum SuggestionType {
    @Schema(description = "Automatically generated by AI")
    AI,
    @Schema(description = "Manually created by a user")
    USER_PROPOSAL,
}
