/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ConfigWorkflowList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-06-09T17:32:21.273+02:00")
public class ConfigWorkflowList {
  @SerializedName("id")
  private String id = null;

  @SerializedName("color")
  private String color = null;

  @SerializedName("hasReceiver")
  private Boolean hasReceiver = false;

  @SerializedName("next")
  private List<String> next = null;

  public ConfigWorkflowList id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ConfigWorkflowList color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(value = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public ConfigWorkflowList hasReceiver(Boolean hasReceiver) {
    this.hasReceiver = hasReceiver;
    return this;
  }

   /**
   * Get hasReceiver
   * @return hasReceiver
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasReceiver() {
    return hasReceiver;
  }

  public void setHasReceiver(Boolean hasReceiver) {
    this.hasReceiver = hasReceiver;
  }

  public ConfigWorkflowList next(List<String> next) {
    this.next = next;
    return this;
  }

  public ConfigWorkflowList addNextItem(String nextItem) {
    if (this.next == null) {
      this.next = new ArrayList<String>();
    }
    this.next.add(nextItem);
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @ApiModelProperty(value = "")
  public List<String> getNext() {
    return next;
  }

  public void setNext(List<String> next) {
    this.next = next;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigWorkflowList configWorkflowList = (ConfigWorkflowList) o;
    return Objects.equals(this.id, configWorkflowList.id) &&
        Objects.equals(this.color, configWorkflowList.color) &&
        Objects.equals(this.hasReceiver, configWorkflowList.hasReceiver) &&
        Objects.equals(this.next, configWorkflowList.next);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, color, hasReceiver, next);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigWorkflowList {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    hasReceiver: ").append(toIndentedString(hasReceiver)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

