/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GroupSignupDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-06-09T17:32:21.273+02:00")
public class GroupSignupDetails {
  /**
   * Gets or Sets signupMethod
   */
  @JsonAdapter(SignupMethodEnum.Adapter.class)
  public enum SignupMethodEnum {
    SIMPLE("simple"),
    
    PASSWORD("password"),
    
    LIST("list");

    private String value;

    SignupMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SignupMethodEnum fromValue(String text) {
      for (SignupMethodEnum b : SignupMethodEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SignupMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SignupMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SignupMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SignupMethodEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("signupMethod")
  private SignupMethodEnum signupMethod = null;

  @SerializedName("signupPassword")
  private String signupPassword = null;

  public GroupSignupDetails signupMethod(SignupMethodEnum signupMethod) {
    this.signupMethod = signupMethod;
    return this;
  }

   /**
   * Get signupMethod
   * @return signupMethod
  **/
  @ApiModelProperty(value = "")
  public SignupMethodEnum getSignupMethod() {
    return signupMethod;
  }

  public void setSignupMethod(SignupMethodEnum signupMethod) {
    this.signupMethod = signupMethod;
  }

  public GroupSignupDetails signupPassword(String signupPassword) {
    this.signupPassword = signupPassword;
    return this;
  }

   /**
   * Get signupPassword
   * @return signupPassword
  **/
  @ApiModelProperty(value = "")
  public String getSignupPassword() {
    return signupPassword;
  }

  public void setSignupPassword(String signupPassword) {
    this.signupPassword = signupPassword;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupSignupDetails groupSignupDetails = (GroupSignupDetails) o;
    return Objects.equals(this.signupMethod, groupSignupDetails.signupMethod) &&
        Objects.equals(this.signupPassword, groupSignupDetails.signupPassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signupMethod, signupPassword);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupSignupDetails {\n");
    
    sb.append("    signupMethod: ").append(toIndentedString(signupMethod)).append("\n");
    sb.append("    signupPassword: ").append(toIndentedString(signupPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

