/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GroupV2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-06-09T17:32:21.273+02:00")
public class GroupV2 {
  /**
   * Gets or Sets rendering
   */
  @JsonAdapter(RenderingEnum.Adapter.class)
  public enum RenderingEnum {
    LEGACY("legacy"),
    
    ANGULAR("angular");

    private String value;

    RenderingEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RenderingEnum fromValue(String text) {
      for (RenderingEnum b : RenderingEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<RenderingEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RenderingEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RenderingEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return RenderingEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("rendering")
  private RenderingEnum rendering = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("views")
  private List<String> views = null;

  public GroupV2 rendering(RenderingEnum rendering) {
    this.rendering = rendering;
    return this;
  }

   /**
   * Get rendering
   * @return rendering
  **/
  @ApiModelProperty(value = "")
  public RenderingEnum getRendering() {
    return rendering;
  }

  public void setRendering(RenderingEnum rendering) {
    this.rendering = rendering;
  }

  public GroupV2 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GroupV2 views(List<String> views) {
    this.views = views;
    return this;
  }

  public GroupV2 addViewsItem(String viewsItem) {
    if (this.views == null) {
      this.views = new ArrayList<String>();
    }
    this.views.add(viewsItem);
    return this;
  }

   /**
   * Get views
   * @return views
  **/
  @ApiModelProperty(value = "")
  public List<String> getViews() {
    return views;
  }

  public void setViews(List<String> views) {
    this.views = views;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupV2 groupV2 = (GroupV2) o;
    return Objects.equals(this.rendering, groupV2.rendering) &&
        Objects.equals(this.id, groupV2.id) &&
        Objects.equals(this.views, groupV2.views);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rendering, id, views);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupV2 {\n");
    
    sb.append("    rendering: ").append(toIndentedString(rendering)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

