/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Level
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class Level {
  @SerializedName("syslogEquivalent")
  private Integer syslogEquivalent = null;

  public Level syslogEquivalent(Integer syslogEquivalent) {
    this.syslogEquivalent = syslogEquivalent;
    return this;
  }

   /**
   * Get syslogEquivalent
   * @return syslogEquivalent
  **/
  @ApiModelProperty(value = "")
  public Integer getSyslogEquivalent() {
    return syslogEquivalent;
  }

  public void setSyslogEquivalent(Integer syslogEquivalent) {
    this.syslogEquivalent = syslogEquivalent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Level level = (Level) o;
    return Objects.equals(this.syslogEquivalent, level.syslogEquivalent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(syslogEquivalent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Level {\n");
    
    sb.append("    syslogEquivalent: ").append(toIndentedString(syslogEquivalent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

