/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LicenseAgreementNode;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LicenseAgreement
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class LicenseAgreement {
  @SerializedName("nodeId")
  private List<LicenseAgreementNode> nodeId = null;

  public LicenseAgreement nodeId(List<LicenseAgreementNode> nodeId) {
    this.nodeId = nodeId;
    return this;
  }

  public LicenseAgreement addNodeIdItem(LicenseAgreementNode nodeIdItem) {
    if (this.nodeId == null) {
      this.nodeId = new ArrayList<LicenseAgreementNode>();
    }
    this.nodeId.add(nodeIdItem);
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  @ApiModelProperty(value = "")
  public List<LicenseAgreementNode> getNodeId() {
    return nodeId;
  }

  public void setNodeId(List<LicenseAgreementNode> nodeId) {
    this.nodeId = nodeId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseAgreement licenseAgreement = (LicenseAgreement) o;
    return Objects.equals(this.nodeId, licenseAgreement.nodeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseAgreement {\n");
    
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

