/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LogoutInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class LogoutInfo {
  @SerializedName("url")
  private String url = null;

  @SerializedName("destroySession")
  private Boolean destroySession = false;

  @SerializedName("ajax")
  private Boolean ajax = false;

  @SerializedName("next")
  private String next = null;

  public LogoutInfo url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public LogoutInfo destroySession(Boolean destroySession) {
    this.destroySession = destroySession;
    return this;
  }

   /**
   * Get destroySession
   * @return destroySession
  **/
  @ApiModelProperty(value = "")
  public Boolean isDestroySession() {
    return destroySession;
  }

  public void setDestroySession(Boolean destroySession) {
    this.destroySession = destroySession;
  }

  public LogoutInfo ajax(Boolean ajax) {
    this.ajax = ajax;
    return this;
  }

   /**
   * Get ajax
   * @return ajax
  **/
  @ApiModelProperty(value = "")
  public Boolean isAjax() {
    return ajax;
  }

  public void setAjax(Boolean ajax) {
    this.ajax = ajax;
  }

  public LogoutInfo next(String next) {
    this.next = next;
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @ApiModelProperty(value = "")
  public String getNext() {
    return next;
  }

  public void setNext(String next) {
    this.next = next;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogoutInfo logoutInfo = (LogoutInfo) o;
    return Objects.equals(this.url, logoutInfo.url) &&
        Objects.equals(this.destroySession, logoutInfo.destroySession) &&
        Objects.equals(this.ajax, logoutInfo.ajax) &&
        Objects.equals(this.next, logoutInfo.next);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, destroySession, ajax, next);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogoutInfo {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    destroySession: ").append(toIndentedString(destroySession)).append("\n");
    sb.append("    ajax: ").append(toIndentedString(ajax)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

