/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MdsForm;
import io.swagger.client.model.MdsList;
import io.swagger.client.model.MdsQueries;
import io.swagger.client.model.MdsRef;
import io.swagger.client.model.MdsType;
import io.swagger.client.model.MdsView;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Mds
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class Mds {
  @SerializedName("types")
  private List<MdsType> types = new ArrayList<MdsType>();

  @SerializedName("ref")
  private MdsRef ref = null;

  @SerializedName("forms")
  private List<MdsForm> forms = new ArrayList<MdsForm>();

  @SerializedName("lists")
  private List<MdsList> lists = new ArrayList<MdsList>();

  @SerializedName("views")
  private List<MdsView> views = new ArrayList<MdsView>();

  @SerializedName("queries")
  private MdsQueries queries = null;

  public Mds types(List<MdsType> types) {
    this.types = types;
    return this;
  }

  public Mds addTypesItem(MdsType typesItem) {
    this.types.add(typesItem);
    return this;
  }

   /**
   * Get types
   * @return types
  **/
  @ApiModelProperty(required = true, value = "")
  public List<MdsType> getTypes() {
    return types;
  }

  public void setTypes(List<MdsType> types) {
    this.types = types;
  }

  public Mds ref(MdsRef ref) {
    this.ref = ref;
    return this;
  }

   /**
   * Get ref
   * @return ref
  **/
  @ApiModelProperty(required = true, value = "")
  public MdsRef getRef() {
    return ref;
  }

  public void setRef(MdsRef ref) {
    this.ref = ref;
  }

  public Mds forms(List<MdsForm> forms) {
    this.forms = forms;
    return this;
  }

  public Mds addFormsItem(MdsForm formsItem) {
    this.forms.add(formsItem);
    return this;
  }

   /**
   * Get forms
   * @return forms
  **/
  @ApiModelProperty(required = true, value = "")
  public List<MdsForm> getForms() {
    return forms;
  }

  public void setForms(List<MdsForm> forms) {
    this.forms = forms;
  }

  public Mds lists(List<MdsList> lists) {
    this.lists = lists;
    return this;
  }

  public Mds addListsItem(MdsList listsItem) {
    this.lists.add(listsItem);
    return this;
  }

   /**
   * Get lists
   * @return lists
  **/
  @ApiModelProperty(required = true, value = "")
  public List<MdsList> getLists() {
    return lists;
  }

  public void setLists(List<MdsList> lists) {
    this.lists = lists;
  }

  public Mds views(List<MdsView> views) {
    this.views = views;
    return this;
  }

  public Mds addViewsItem(MdsView viewsItem) {
    this.views.add(viewsItem);
    return this;
  }

   /**
   * Get views
   * @return views
  **/
  @ApiModelProperty(required = true, value = "")
  public List<MdsView> getViews() {
    return views;
  }

  public void setViews(List<MdsView> views) {
    this.views = views;
  }

  public Mds queries(MdsQueries queries) {
    this.queries = queries;
    return this;
  }

   /**
   * Get queries
   * @return queries
  **/
  @ApiModelProperty(required = true, value = "")
  public MdsQueries getQueries() {
    return queries;
  }

  public void setQueries(MdsQueries queries) {
    this.queries = queries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mds mds = (Mds) o;
    return Objects.equals(this.types, mds.types) &&
        Objects.equals(this.ref, mds.ref) &&
        Objects.equals(this.forms, mds.forms) &&
        Objects.equals(this.lists, mds.lists) &&
        Objects.equals(this.views, mds.views) &&
        Objects.equals(this.queries, mds.queries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(types, ref, forms, lists, views, queries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mds {\n");
    
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    forms: ").append(toIndentedString(forms)).append("\n");
    sb.append("    lists: ").append(toIndentedString(lists)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("    queries: ").append(toIndentedString(queries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

