/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MdsRef;
import java.io.IOException;

/**
 * MdsDesc
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-19T15:56:50.258+01:00")
public class MdsDesc {
  @SerializedName("ref")
  private MdsRef ref = null;

  @SerializedName("isDefaultMds")
  private Boolean isDefaultMds = false;

  public MdsDesc ref(MdsRef ref) {
    this.ref = ref;
    return this;
  }

   /**
   * Get ref
   * @return ref
  **/
  @ApiModelProperty(required = true, value = "")
  public MdsRef getRef() {
    return ref;
  }

  public void setRef(MdsRef ref) {
    this.ref = ref;
  }

  public MdsDesc isDefaultMds(Boolean isDefaultMds) {
    this.isDefaultMds = isDefaultMds;
    return this;
  }

   /**
   * Get isDefaultMds
   * @return isDefaultMds
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean isIsDefaultMds() {
    return isDefaultMds;
  }

  public void setIsDefaultMds(Boolean isDefaultMds) {
    this.isDefaultMds = isDefaultMds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MdsDesc mdsDesc = (MdsDesc) o;
    return Objects.equals(this.ref, mdsDesc.ref) &&
        Objects.equals(this.isDefaultMds, mdsDesc.isDefaultMds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ref, isDefaultMds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MdsDesc {\n");
    
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    isDefaultMds: ").append(toIndentedString(isDefaultMds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

