/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MdsListPropertyParameter;
import io.swagger.client.model.MdsListPropertyValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MdsListProperty
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class MdsListProperty {
  @SerializedName("name")
  private String name = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("labelHint")
  private String labelHint = null;

  @SerializedName("formHeight")
  private String formHeight = null;

  @SerializedName("formLength")
  private String formLength = null;

  @SerializedName("widget")
  private String widget = null;

  @SerializedName("widgetTitle")
  private String widgetTitle = null;

  @SerializedName("copyFrom")
  private List<String> copyFrom = new ArrayList<String>();

  @SerializedName("parameters")
  private List<MdsListPropertyParameter> parameters = new ArrayList<MdsListPropertyParameter>();

  @SerializedName("values")
  private List<MdsListPropertyValue> values = new ArrayList<MdsListPropertyValue>();

  @SerializedName("defaultValues")
  private List<String> defaultValues = new ArrayList<String>();

  @SerializedName("multiple")
  private Boolean multiple = false;

  @SerializedName("placeHolder")
  private String placeHolder = null;

  @SerializedName("styleName")
  private String styleName = null;

  @SerializedName("styleNameLabel")
  private String styleNameLabel = null;

  @SerializedName("type")
  private String type = null;

  public MdsListProperty name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MdsListProperty label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public MdsListProperty labelHint(String labelHint) {
    this.labelHint = labelHint;
    return this;
  }

   /**
   * Get labelHint
   * @return labelHint
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLabelHint() {
    return labelHint;
  }

  public void setLabelHint(String labelHint) {
    this.labelHint = labelHint;
  }

  public MdsListProperty formHeight(String formHeight) {
    this.formHeight = formHeight;
    return this;
  }

   /**
   * Get formHeight
   * @return formHeight
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFormHeight() {
    return formHeight;
  }

  public void setFormHeight(String formHeight) {
    this.formHeight = formHeight;
  }

  public MdsListProperty formLength(String formLength) {
    this.formLength = formLength;
    return this;
  }

   /**
   * Get formLength
   * @return formLength
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFormLength() {
    return formLength;
  }

  public void setFormLength(String formLength) {
    this.formLength = formLength;
  }

  public MdsListProperty widget(String widget) {
    this.widget = widget;
    return this;
  }

   /**
   * Get widget
   * @return widget
  **/
  @ApiModelProperty(required = true, value = "")
  public String getWidget() {
    return widget;
  }

  public void setWidget(String widget) {
    this.widget = widget;
  }

  public MdsListProperty widgetTitle(String widgetTitle) {
    this.widgetTitle = widgetTitle;
    return this;
  }

   /**
   * Get widgetTitle
   * @return widgetTitle
  **/
  @ApiModelProperty(required = true, value = "")
  public String getWidgetTitle() {
    return widgetTitle;
  }

  public void setWidgetTitle(String widgetTitle) {
    this.widgetTitle = widgetTitle;
  }

  public MdsListProperty copyFrom(List<String> copyFrom) {
    this.copyFrom = copyFrom;
    return this;
  }

  public MdsListProperty addCopyFromItem(String copyFromItem) {
    this.copyFrom.add(copyFromItem);
    return this;
  }

   /**
   * Get copyFrom
   * @return copyFrom
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getCopyFrom() {
    return copyFrom;
  }

  public void setCopyFrom(List<String> copyFrom) {
    this.copyFrom = copyFrom;
  }

  public MdsListProperty parameters(List<MdsListPropertyParameter> parameters) {
    this.parameters = parameters;
    return this;
  }

  public MdsListProperty addParametersItem(MdsListPropertyParameter parametersItem) {
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @ApiModelProperty(required = true, value = "")
  public List<MdsListPropertyParameter> getParameters() {
    return parameters;
  }

  public void setParameters(List<MdsListPropertyParameter> parameters) {
    this.parameters = parameters;
  }

  public MdsListProperty values(List<MdsListPropertyValue> values) {
    this.values = values;
    return this;
  }

  public MdsListProperty addValuesItem(MdsListPropertyValue valuesItem) {
    this.values.add(valuesItem);
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  @ApiModelProperty(required = true, value = "")
  public List<MdsListPropertyValue> getValues() {
    return values;
  }

  public void setValues(List<MdsListPropertyValue> values) {
    this.values = values;
  }

  public MdsListProperty defaultValues(List<String> defaultValues) {
    this.defaultValues = defaultValues;
    return this;
  }

  public MdsListProperty addDefaultValuesItem(String defaultValuesItem) {
    this.defaultValues.add(defaultValuesItem);
    return this;
  }

   /**
   * Get defaultValues
   * @return defaultValues
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getDefaultValues() {
    return defaultValues;
  }

  public void setDefaultValues(List<String> defaultValues) {
    this.defaultValues = defaultValues;
  }

  public MdsListProperty multiple(Boolean multiple) {
    this.multiple = multiple;
    return this;
  }

   /**
   * Get multiple
   * @return multiple
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean isMultiple() {
    return multiple;
  }

  public void setMultiple(Boolean multiple) {
    this.multiple = multiple;
  }

  public MdsListProperty placeHolder(String placeHolder) {
    this.placeHolder = placeHolder;
    return this;
  }

   /**
   * Get placeHolder
   * @return placeHolder
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPlaceHolder() {
    return placeHolder;
  }

  public void setPlaceHolder(String placeHolder) {
    this.placeHolder = placeHolder;
  }

  public MdsListProperty styleName(String styleName) {
    this.styleName = styleName;
    return this;
  }

   /**
   * Get styleName
   * @return styleName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getStyleName() {
    return styleName;
  }

  public void setStyleName(String styleName) {
    this.styleName = styleName;
  }

  public MdsListProperty styleNameLabel(String styleNameLabel) {
    this.styleNameLabel = styleNameLabel;
    return this;
  }

   /**
   * Get styleNameLabel
   * @return styleNameLabel
  **/
  @ApiModelProperty(required = true, value = "")
  public String getStyleNameLabel() {
    return styleNameLabel;
  }

  public void setStyleNameLabel(String styleNameLabel) {
    this.styleNameLabel = styleNameLabel;
  }

  public MdsListProperty type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MdsListProperty mdsListProperty = (MdsListProperty) o;
    return Objects.equals(this.name, mdsListProperty.name) &&
        Objects.equals(this.label, mdsListProperty.label) &&
        Objects.equals(this.labelHint, mdsListProperty.labelHint) &&
        Objects.equals(this.formHeight, mdsListProperty.formHeight) &&
        Objects.equals(this.formLength, mdsListProperty.formLength) &&
        Objects.equals(this.widget, mdsListProperty.widget) &&
        Objects.equals(this.widgetTitle, mdsListProperty.widgetTitle) &&
        Objects.equals(this.copyFrom, mdsListProperty.copyFrom) &&
        Objects.equals(this.parameters, mdsListProperty.parameters) &&
        Objects.equals(this.values, mdsListProperty.values) &&
        Objects.equals(this.defaultValues, mdsListProperty.defaultValues) &&
        Objects.equals(this.multiple, mdsListProperty.multiple) &&
        Objects.equals(this.placeHolder, mdsListProperty.placeHolder) &&
        Objects.equals(this.styleName, mdsListProperty.styleName) &&
        Objects.equals(this.styleNameLabel, mdsListProperty.styleNameLabel) &&
        Objects.equals(this.type, mdsListProperty.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, label, labelHint, formHeight, formLength, widget, widgetTitle, copyFrom, parameters, values, defaultValues, multiple, placeHolder, styleName, styleNameLabel, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MdsListProperty {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    labelHint: ").append(toIndentedString(labelHint)).append("\n");
    sb.append("    formHeight: ").append(toIndentedString(formHeight)).append("\n");
    sb.append("    formLength: ").append(toIndentedString(formLength)).append("\n");
    sb.append("    widget: ").append(toIndentedString(widget)).append("\n");
    sb.append("    widgetTitle: ").append(toIndentedString(widgetTitle)).append("\n");
    sb.append("    copyFrom: ").append(toIndentedString(copyFrom)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    defaultValues: ").append(toIndentedString(defaultValues)).append("\n");
    sb.append("    multiple: ").append(toIndentedString(multiple)).append("\n");
    sb.append("    placeHolder: ").append(toIndentedString(placeHolder)).append("\n");
    sb.append("    styleName: ").append(toIndentedString(styleName)).append("\n");
    sb.append("    styleNameLabel: ").append(toIndentedString(styleNameLabel)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

