/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NodeRef
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class NodeRef {
  @SerializedName("repo")
  private String repo = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("archived")
  private Boolean archived = false;

  @SerializedName("isHomeRepo")
  private Boolean isHomeRepo = false;

  public NodeRef repo(String repo) {
    this.repo = repo;
    return this;
  }

   /**
   * Get repo
   * @return repo
  **/
  @ApiModelProperty(required = true, value = "")
  public String getRepo() {
    return repo;
  }

  public void setRepo(String repo) {
    this.repo = repo;
  }

  public NodeRef id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public NodeRef archived(Boolean archived) {
    this.archived = archived;
    return this;
  }

   /**
   * Get archived
   * @return archived
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean isArchived() {
    return archived;
  }

  public void setArchived(Boolean archived) {
    this.archived = archived;
  }

  public NodeRef isHomeRepo(Boolean isHomeRepo) {
    this.isHomeRepo = isHomeRepo;
    return this;
  }

   /**
   * Get isHomeRepo
   * @return isHomeRepo
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsHomeRepo() {
    return isHomeRepo;
  }

  public void setIsHomeRepo(Boolean isHomeRepo) {
    this.isHomeRepo = isHomeRepo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeRef nodeRef = (NodeRef) o;
    return Objects.equals(this.repo, nodeRef.repo) &&
        Objects.equals(this.id, nodeRef.id) &&
        Objects.equals(this.archived, nodeRef.archived) &&
        Objects.equals(this.isHomeRepo, nodeRef.isHomeRepo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repo, id, archived, isHomeRepo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeRef {\n");
    
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    isHomeRepo: ").append(toIndentedString(isHomeRepo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

