/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PersonDeleteOptions;
import io.swagger.client.model.PersonDeleteResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PersonReport
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class PersonReport {
  @SerializedName("options")
  private PersonDeleteOptions options = null;

  @SerializedName("results")
  private List<PersonDeleteResult> results = null;

  public PersonReport options(PersonDeleteOptions options) {
    this.options = options;
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @ApiModelProperty(value = "")
  public PersonDeleteOptions getOptions() {
    return options;
  }

  public void setOptions(PersonDeleteOptions options) {
    this.options = options;
  }

  public PersonReport results(List<PersonDeleteResult> results) {
    this.results = results;
    return this;
  }

  public PersonReport addResultsItem(PersonDeleteResult resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<PersonDeleteResult>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(value = "")
  public List<PersonDeleteResult> getResults() {
    return results;
  }

  public void setResults(List<PersonDeleteResult> results) {
    this.results = results;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonReport personReport = (PersonReport) o;
    return Objects.equals(this.options, personReport.options) &&
        Objects.equals(this.results, personReport.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(options, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonReport {\n");
    
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

