/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Frontpage;
import java.io.IOException;

/**
 * RepositoryConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class RepositoryConfig {
  @SerializedName("frontpage")
  private Frontpage frontpage = null;

  public RepositoryConfig frontpage(Frontpage frontpage) {
    this.frontpage = frontpage;
    return this;
  }

   /**
   * Get frontpage
   * @return frontpage
  **/
  @ApiModelProperty(value = "")
  public Frontpage getFrontpage() {
    return frontpage;
  }

  public void setFrontpage(Frontpage frontpage) {
    this.frontpage = frontpage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryConfig repositoryConfig = (RepositoryConfig) o;
    return Objects.equals(this.frontpage, repositoryConfig.frontpage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frontpage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryConfig {\n");
    
    sb.append("    frontpage: ").append(toIndentedString(frontpage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

