/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Authority;
import io.swagger.client.model.Serializable;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Tracking
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class Tracking {
  @SerializedName("counts")
  private Map<String, Integer> counts = null;

  @SerializedName("date")
  private String date = null;

  @SerializedName("authority")
  private Authority authority = null;

  @SerializedName("fields")
  private Map<String, Serializable> fields = null;

  @SerializedName("groups")
  private Map<String, Map<String, Long>> groups = null;

  public Tracking counts(Map<String, Integer> counts) {
    this.counts = counts;
    return this;
  }

  public Tracking putCountsItem(String key, Integer countsItem) {
    if (this.counts == null) {
      this.counts = new HashMap<String, Integer>();
    }
    this.counts.put(key, countsItem);
    return this;
  }

   /**
   * Get counts
   * @return counts
  **/
  @ApiModelProperty(value = "")
  public Map<String, Integer> getCounts() {
    return counts;
  }

  public void setCounts(Map<String, Integer> counts) {
    this.counts = counts;
  }

  public Tracking date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Tracking authority(Authority authority) {
    this.authority = authority;
    return this;
  }

   /**
   * Get authority
   * @return authority
  **/
  @ApiModelProperty(value = "")
  public Authority getAuthority() {
    return authority;
  }

  public void setAuthority(Authority authority) {
    this.authority = authority;
  }

  public Tracking fields(Map<String, Serializable> fields) {
    this.fields = fields;
    return this;
  }

  public Tracking putFieldsItem(String key, Serializable fieldsItem) {
    if (this.fields == null) {
      this.fields = new HashMap<String, Serializable>();
    }
    this.fields.put(key, fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @ApiModelProperty(value = "")
  public Map<String, Serializable> getFields() {
    return fields;
  }

  public void setFields(Map<String, Serializable> fields) {
    this.fields = fields;
  }

  public Tracking groups(Map<String, Map<String, Long>> groups) {
    this.groups = groups;
    return this;
  }

  public Tracking putGroupsItem(String key, Map<String, Long> groupsItem) {
    if (this.groups == null) {
      this.groups = new HashMap<String, Map<String, Long>>();
    }
    this.groups.put(key, groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public Map<String, Map<String, Long>> getGroups() {
    return groups;
  }

  public void setGroups(Map<String, Map<String, Long>> groups) {
    this.groups = groups;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tracking tracking = (Tracking) o;
    return Objects.equals(this.counts, tracking.counts) &&
        Objects.equals(this.date, tracking.date) &&
        Objects.equals(this.authority, tracking.authority) &&
        Objects.equals(this.fields, tracking.fields) &&
        Objects.equals(this.groups, tracking.groups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(counts, date, authority, fields, groups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tracking {\n");
    
    sb.append("    counts: ").append(toIndentedString(counts)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

