/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Group;
import io.swagger.client.model.Organization;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TrackingAuthority
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-06-09T17:32:21.273+02:00")
public class TrackingAuthority {
  @SerializedName("hash")
  private String hash = null;

  @SerializedName("organization")
  private List<Organization> organization = null;

  @SerializedName("mediacenter")
  private List<Group> mediacenter = null;

  public TrackingAuthority hash(String hash) {
    this.hash = hash;
    return this;
  }

   /**
   * Get hash
   * @return hash
  **/
  @ApiModelProperty(value = "")
  public String getHash() {
    return hash;
  }

  public void setHash(String hash) {
    this.hash = hash;
  }

  public TrackingAuthority organization(List<Organization> organization) {
    this.organization = organization;
    return this;
  }

  public TrackingAuthority addOrganizationItem(Organization organizationItem) {
    if (this.organization == null) {
      this.organization = new ArrayList<Organization>();
    }
    this.organization.add(organizationItem);
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @ApiModelProperty(value = "")
  public List<Organization> getOrganization() {
    return organization;
  }

  public void setOrganization(List<Organization> organization) {
    this.organization = organization;
  }

  public TrackingAuthority mediacenter(List<Group> mediacenter) {
    this.mediacenter = mediacenter;
    return this;
  }

  public TrackingAuthority addMediacenterItem(Group mediacenterItem) {
    if (this.mediacenter == null) {
      this.mediacenter = new ArrayList<Group>();
    }
    this.mediacenter.add(mediacenterItem);
    return this;
  }

   /**
   * Get mediacenter
   * @return mediacenter
  **/
  @ApiModelProperty(value = "")
  public List<Group> getMediacenter() {
    return mediacenter;
  }

  public void setMediacenter(List<Group> mediacenter) {
    this.mediacenter = mediacenter;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackingAuthority trackingAuthority = (TrackingAuthority) o;
    return Objects.equals(this.hash, trackingAuthority.hash) &&
        Objects.equals(this.organization, trackingAuthority.organization) &&
        Objects.equals(this.mediacenter, trackingAuthority.mediacenter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hash, organization, mediacenter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackingAuthority {\n");
    
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    mediacenter: ").append(toIndentedString(mediacenter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

