/*
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.User;
import java.io.IOException;

/**
 * UserEntry
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-20T14:32:44.166+01:00")
public class UserEntry {
  @SerializedName("editProfile")
  private Boolean editProfile = false;

  @SerializedName("person")
  private User person = null;

  public UserEntry editProfile(Boolean editProfile) {
    this.editProfile = editProfile;
    return this;
  }

   /**
   * Get editProfile
   * @return editProfile
  **/
  @ApiModelProperty(value = "")
  public Boolean isEditProfile() {
    return editProfile;
  }

  public void setEditProfile(Boolean editProfile) {
    this.editProfile = editProfile;
  }

  public UserEntry person(User person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @ApiModelProperty(required = true, value = "")
  public User getPerson() {
    return person;
  }

  public void setPerson(User person) {
    this.person = person;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserEntry userEntry = (UserEntry) o;
    return Objects.equals(this.editProfile, userEntry.editProfile) &&
        Objects.equals(this.person, userEntry.person);
  }

  @Override
  public int hashCode() {
    return Objects.hash(editProfile, person);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEntry {\n");
    
    sb.append("    editProfile: ").append(toIndentedString(editProfile)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

