import { CommonModule } from '@angular/common';
import {
    Component,
    CUSTOM_ELEMENTS_SCHEMA,
    input,
    Input,
    InputSignal,
    OnChanges,
    OnInit,
    signal,
    SimpleChanges,
    ViewEncapsulation,
    WritableSignal,
} from '@angular/core';
import { TranslateModule } from '@ngx-translate/core';
import { Node, ParentEntries } from 'ngx-edu-sharing-api';
import { ChatCompletionResult } from 'ngx-edu-sharing-b-api';
import {
    ColorHelper,
    EduSharingUiCommonModule,
    PreferredColor,
    SpinnerComponent,
    UIConstants,
} from 'ngx-edu-sharing-ui';
import { RestConstants } from '../../../../core-module/rest/rest-constants';
import { SharedModule } from '../../../../shared/shared.module';
import { TooltipAriaLabelDirective } from '../../shared/directives/tooltip-aria-label.directive';
import { HighlightSearchPipe } from '../../shared/pipes/highlight-search.pipe';
import { AiHelperService } from '../../shared/services/ai-helper.service';
import { GlobalWidgetConfigService } from '../../shared/services/global-widget-config.service';
import { TopicPageHelperService } from '../../shared/services/topic-page-helper.service';
import { DEFAULT_WIDGET_CONFIG_PROP } from '../../shared/types/custom-definitions';
import { TopicHeaderConfig } from '../../shared/types/widget-config/topic-header-config';
import { retrieveResultString } from '../../shared/utils/ai-util';
import { getNodeOrDefaultNodeId } from '../../shared/utils/node-util';
import { retrieveNodeId } from '../../shared/utils/template-util';
import { ColorPickerComponent } from '../shared/color-picker/color-picker.component';
import { EditableTextComponent } from '../shared/editable-text/editable-text.component';
import { ImageWrapperComponent } from '../shared/image-wrapper/image-wrapper.component';

@Component({
    selector: 'es-topic-header',
    encapsulation: ViewEncapsulation.Emulated,
    imports: [
        CommonModule,
        EduSharingUiCommonModule,
        ColorPickerComponent,
        EditableTextComponent,
        HighlightSearchPipe,
        ImageWrapperComponent,
        SharedModule,
        SpinnerComponent,
        TooltipAriaLabelDirective,
        TranslateModule,
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    templateUrl: './topic-header.component.html',
    styleUrls: ['./topic-header.component.scss'],
})
export class TopicHeaderComponent implements OnChanges, OnInit {
    // CONSTANTS
    private readonly DEFAULT_DESCRIPTION: string = '';
    readonly DEFAULT_HEADER_TEXT_BG_COLOR = '#FFFFFF';
    readonly i18nPrefix: string = 'TOPIC_PAGE.WIDGET.TOPIC_HEADER.';

    private _collectionNode: Node = null;
    @Input() set collectionNode(value: Node) {
        this._collectionNode = value;
        this.collectionDescription = value?.properties?.[RestConstants.CM_DESCRIPTION]?.[0];
        if (!this.collectionDescription) {
            void this.generateCollectionDescription(retrieveNodeId(value));
        }
    }
    get collectionNode(): Node {
        return this._collectionNode;
    }
    @Input() contextNodeId: string;
    @Input() defaultDescriptionNodeId?: string = '';
    @Input() defaultImageNodeId?: string = '';
    @Input() defaultTextNodeId?: string = '';
    private _editMode: boolean = false;
    @Input() get editMode(): boolean {
        return this._editMode;
    }
    set editMode(val: boolean) {
        this.setEditMode(val);
    }
    @Input() nodeId: string = '';
    @Input() pageVariantNode: Node;
    parentEntries: InputSignal<ParentEntries> = input<ParentEntries>(null);
    searchInput: InputSignal<string> = input<string>(null);
    @Input() topic: string;

    aiGeneratedDescription: WritableSignal<boolean> = signal(false);
    aiGeneratedImage: boolean;
    aiGeneratedText: WritableSignal<boolean> = signal(false);
    aiSupported: WritableSignal<boolean> = signal(false);
    collectionDescription: string;
    private configLocked: boolean = false;
    // description is used for the "description" of importance (stored in a "header" widget node)
    description: string = this.DEFAULT_DESCRIPTION;
    initialized: WritableSignal<boolean> = signal(false);
    textBackgroundColor: string = this.DEFAULT_HEADER_TEXT_BG_COLOR;
    userUploadedNodeId: string = null;
    widgetNodeId: string = null;

    constructor(
        private aiHelperService: AiHelperService,
        private globalWidgetConfigService: GlobalWidgetConfigService,
        private topicPageHelperService: TopicPageHelperService,
    ) {}

    /**
     * Initializes the component.
     */
    async ngOnInit(): Promise<void> {
        // retrieve the widget node ID for a potential AI request
        this.widgetNodeId = getNodeOrDefaultNodeId(
            this.defaultImageNodeId,
            this.globalWidgetConfigService.defaultTopicHeaderImageWidgetNodeId,
        );
        // by default, the image should be generated by AI if it is supported
        this.aiSupported.set(await this.aiHelperService.hasAISupport());
        this.aiGeneratedImage = this.aiSupported();
    }

    /**
     * Initializes or updates the topic header component.
     *
     * @param changes
     */
    async ngOnChanges(changes: SimpleChanges): Promise<void> {
        const topicChanged: boolean = changes.topic && !changes.topic?.firstChange;
        if (
            changes.nodeId?.firstChange ||
            changes.nodeId?.currentValue !== changes.nodeId?.previousValue ||
            topicChanged
        ) {
            // reset several variables if an actual change was detected
            if (
                (!changes.nodeId?.firstChange &&
                    changes.nodeId?.currentValue !== changes.nodeId?.previousValue) ||
                topicChanged
            ) {
                this.aiGeneratedImage = this.aiSupported();
                this.aiGeneratedText.set(false);
                this.initialized.set(false);
                this.description = this.DEFAULT_DESCRIPTION;
                this.textBackgroundColor = this.DEFAULT_HEADER_TEXT_BG_COLOR;
                this.userUploadedNodeId = null;
            }
            // initialize the topic header component
            await this.initTopicHeader();
        }
        if (!changes.editMode?.firstChange && changes.editMode?.currentValue === false) {
            // regenerate texts of the topic header component
            await this.regenerateTexts();
        }
    }

    /**
     * Initializes the topic header by generating an introductory text or retrieving it from the config.
     */
    async initTopicHeader(): Promise<void> {
        // retrieve a config node if one exists
        let configJson: string = '{}';
        if (this.nodeId) {
            const node: Node = await this.topicPageHelperService.getNode(this.nodeId);
            if (node.properties?.[DEFAULT_WIDGET_CONFIG_PROP]?.[0]) {
                configJson = node.properties[DEFAULT_WIDGET_CONFIG_PROP][0];
            }
        }
        // read config from this JSON string and generates an AI text if no description is found
        const aiNodeId: string = getNodeOrDefaultNodeId(
            this.defaultTextNodeId,
            this.globalWidgetConfigService.defaultTopicHeaderTextWidgetNodeId,
        );
        await this.readConfigFromJson(configJson, aiNodeId);
        // set the component to be initialized (further processing is done in the child component)
        this.initialized.set(true);
    }

    /**
     * Regenerates collectionDescription and description via AI if they were cleared.
     */
    async regenerateTexts(): Promise<void> {
        if (!this.collectionDescription) {
            await this.generateCollectionDescription(retrieveNodeId(this._collectionNode));
        }
        if (!this.description) {
            const aiNodeId: string = getNodeOrDefaultNodeId(
                this.defaultTextNodeId,
                this.globalWidgetConfigService.defaultTopicHeaderTextWidgetNodeId,
            );
            await this.generateDescription(aiNodeId);
        }
    }

    /**
     * Changes the text background color by emitting a persist config event.
     */
    async changeTextBackgroundColor(color: string): Promise<void> {
        if (color !== this.textBackgroundColor) {
            this.textBackgroundColor = color;
            await this.persistConfig();
        }
    }

    /**
     * Persists the currently defined config.
     */
    async persistConfig(): Promise<void> {
        if (this.configLocked) {
            return;
        }
        // retrieve a widget config from the currently set variables
        const widgetConfig: TopicHeaderConfig = this.retrieveWidgetConfig();
        // ensure that the config is not attempted to be stored twice
        this.configLocked = true;
        setTimeout((): void => {
            this.configLocked = false;
        }, 500);
        // persist the config by creating a new or updating an existing node
        await this.topicPageHelperService.persistConfig(
            this.nodeId,
            -1,
            -1,
            this.pageVariantNode,
            widgetConfig,
            null,
            this.contextNodeId,
            false,
            true,
        );
    }

    /**
     * Persists the description of the collection.
     */
    async persistCollectionDescription(description: string): Promise<void> {
        if (this.configLocked) {
            return;
        }
        // ensure that the config is not attempted to be stored twice
        this.configLocked = true;
        setTimeout((): void => {
            this.configLocked = false;
        }, 500);
        if (!this.collectionNode?.ref.id) {
            return;
        }
        try {
            this.topicPageHelperService.openSaveConfigToast();
            await this.topicPageHelperService.setProperty(
                this.collectionNode.ref.id,
                RestConstants.CM_DESCRIPTION,
                description,
            );
        } catch (err) {
            this.topicPageHelperService.displayErrorToast(err);
        }
    }

    /**
     * Helper function to generate the description of a collection.
     *
     * @param contextNodeId
     */
    private async generateCollectionDescription(contextNodeId: string): Promise<void> {
        if (!(await this.aiHelperService.hasAISupport())) {
            return;
        }
        const mdsConfigId: string = getNodeOrDefaultNodeId(
            this.defaultDescriptionNodeId,
            this.globalWidgetConfigService.defaultTopicHeaderDescriptionWidgetNodeId,
        );
        const promptResponse: ChatCompletionResult = await this.aiHelperService.generateFromPrompt(
            mdsConfigId,
            {},
            this.contextNodeId || contextNodeId,
        );
        const responseText: string = retrieveResultString(promptResponse) ?? '';
        if (responseText !== '') {
            this.configLocked = true;
            this.collectionDescription = responseText;
            this.aiGeneratedDescription.set(true);
            setTimeout((): void => {
                this.configLocked = false;
            }, 1000);
        }
    }

    /**
     * Helper function to set the edit mode and lock the config.
     *
     * @param editMode
     */
    private setEditMode(editMode: boolean): void {
        this.configLocked = true;
        this._editMode = editMode;
        setTimeout((): void => {
            this.configLocked = false;
        }, 1000);
    }

    /**
     * Helper function to read the config from a given string.
     *
     * @param configString
     * @param nodeId
     */
    private async readConfigFromJson(configString: string, nodeId: string): Promise<void> {
        const config: TopicHeaderConfig = JSON.parse(configString);
        // this is the case if a widgetNode for the header exists
        if (config.description) {
            this.description = config.description;
            this.aiGeneratedText.set(false);
        } else {
            await this.generateDescription(nodeId);
        }
        // check whether an AI-generated image is explicitly set to false
        if (config.aiGeneratedImage === false) {
            this.aiGeneratedImage = false;
        }
        // check whether a text background color is explicitly set
        if (
            config.textBackgroundColor &&
            config.textBackgroundColor !== this.DEFAULT_HEADER_TEXT_BG_COLOR
        ) {
            this.textBackgroundColor = config.textBackgroundColor;
        }
        // check if an image was uploaded
        if (config.userUploadedNodeId) {
            this.userUploadedNodeId = config.userUploadedNodeId;
        }
    }

    /**
     * Helper function to generate the description text via AI.
     *
     * @param nodeId
     */
    private async generateDescription(nodeId: string): Promise<void> {
        if (!(await this.aiHelperService.hasAISupport())) {
            return;
        }
        const promptResponse: ChatCompletionResult = await this.aiHelperService.generateFromPrompt(
            nodeId,
            {},
            this.contextNodeId,
        );
        const responseText: string = retrieveResultString(promptResponse) ?? '';
        if (responseText !== '') {
            this.configLocked = true;
            this.description = responseText;
            this.aiGeneratedText.set(true);
            setTimeout((): void => {
                this.configLocked = false;
            }, 1000);
        }
    }

    /**
     * Helper function to retrieve a widget config from the currently set variables in the component.
     */
    private retrieveWidgetConfig(): TopicHeaderConfig {
        const headerConfig: TopicHeaderConfig = {
            aiGeneratedImage: this.aiGeneratedImage,
            description: this.description,
            userUploadedNodeId: this.userUploadedNodeId,
        };
        if (this.textBackgroundColor) {
            headerConfig.textBackgroundColor = this.textBackgroundColor;
        }
        return headerConfig;
    }

    /**
     * Checks whether a given color is dark.
     *
     * @param color
     */
    isDarkColor(color: string) {
        return ColorHelper.getPreferredColor(color) === PreferredColor.Black;
    }

    protected readonly ROUTER_PREFIX: string = UIConstants.ROUTER_PREFIX;
}
