/**
 *
 *  
 * 
 * 
 *	
 *
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 *
 */
package org.edu_sharing.repository.server.jobs.quartz;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.alfresco.service.ServiceRegistry;
import org.alfresco.service.namespace.QName;
import org.apache.log4j.Logger;
import org.edu_sharing.alfrescocontext.gate.AlfAppContextGate;
import org.edu_sharing.repository.server.jobs.helper.NodeRunner;
import org.edu_sharing.repository.server.jobs.quartz.annotation.JobDescription;
import org.edu_sharing.repository.server.jobs.quartz.annotation.JobFieldDescription;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;
import org.springframework.context.ApplicationContext;

import java.io.*;
import java.util.*;
import java.util.stream.Collectors;

import java.util.function.Function;

@JobDescription(description = "Serialize all metadata of nodes and persistent them as a file")
public class SerializeMetadataJob extends AbstractJobMapAnnotationParams{
	protected Logger logger = Logger.getLogger(SerializeMetadataJob.class);
	@JobFieldDescription(description = "target output filename, when empty will be generated by current timestamp")
	private String filename;
	@JobFieldDescription(description = "folder id to start from")
	private String startFolder;
	@Override
	public void executeInternal(JobExecutionContext context) throws JobExecutionException {

		ApplicationContext applicationContext = AlfAppContextGate.getApplicationContext();

		ServiceRegistry serviceRegistry = (ServiceRegistry) applicationContext.getBean(ServiceRegistry.SERVICE_REGISTRY);
		NodeRunner runner = new NodeRunner();
		runner.setRunAsSystem(true);
		runner.setTransaction(NodeRunner.TransactionMode.Local);
		runner.setThreaded(false);
		String TMP_DIR = System.getProperty("java.io.tmpdir");
		if(filename==null || filename.isEmpty()) {
			filename = "metadata_export_" + System.currentTimeMillis() + ".json";
		}
		if(startFolder != null) {
			runner.setStartFolder(startFolder);
		}
		File file = new File(TMP_DIR, filename);
		try(OutputStreamWriter oos = new OutputStreamWriter(new FileOutputStream(file))) {
			List<AlfrescoNodeModel> nodes = new ArrayList<>();
			runner.setTask((nodeRef) -> {
				if(isInterrupted()) {
					return;
				}
				try {
					AlfrescoNodeModel model = new AlfrescoNodeModel();
					model.type = serviceRegistry.getNodeService().getType(nodeRef).toString();
					model.aspects = serviceRegistry.getNodeService().getAspects(nodeRef).stream().map(QName::toString).collect(Collectors.toSet());
					Map<QName, Serializable> props = serviceRegistry.getNodeService().getProperties(nodeRef);
					Map<String, Serializable> map = new HashMap<>();
					props.forEach((key, value) -> map.put(key.toString(), value));
					model.properties = map;
					//oos.writeObject(model);
					nodes.add(model);
					//logger.info("Wrote node " + nodeRef);
				} catch (Throwable e) {
					logger.warn(e.getMessage(), e);
				}
			});
			runner.run();

			LogDistinctProperties(nodes);

			Gson gson = new GsonBuilder().setPrettyPrinting().create();
			oos.write(gson.toJson(nodes));
			logger.info("Wrote data to " +file);
			logger.info("Test");
		} catch(Exception e) {
			logger.error(e.getMessage(), e);
		}
	}

	private void LogDistinctProperties(List<AlfrescoNodeModel> nodes){
		String allMetaDataKeys = nodes.stream()
				.flatMap(x -> x.properties.entrySet().stream())
				.collect(Collectors.groupingBy(Map.Entry<String, Serializable>::getKey,
						Collectors.mapping(Map.Entry<String, Serializable>::getValue,
								Collectors.reducing(null, Function.identity(), (first, last) -> {
									if (first == null) {
										return last;
									}
									if (first instanceof String && ((String) first).isEmpty()) {
										return last;
									}
									if (first instanceof List) {
										List list = (List) first;
										if (list.size() == 0 || (list.get(0) instanceof String && ((String) list.get(0)).isEmpty())) {
											return last;
										}
									}
									return first;
								}))))
				.entrySet()
				.stream()
				.collect(Collectors.toMap(Map.Entry<String, Serializable>::getKey, p -> "put(\""+p.getKey() + "\", " + Optional.of(p).map(Map.Entry::getValue).map(Object::toString).map(x->x.replace("\n", "| ")).orElse("") + "); // " + Optional.of(p).map(Map.Entry::getValue).map(Object::getClass).map(Class::getName).orElse(""), (p, q) -> p))
				.values()
				.stream()
				.sorted()
				.collect(Collectors.joining("\n"));
		logger.info(allMetaDataKeys);
	}

	public static class AlfrescoNodeModel implements Serializable {
		public String type;
		public Set<String> aspects;
		public Map<String, Serializable> properties;
	}

}
