/**
 *
 *  
 * 
 * 
 *	
 *
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 *
 */
package org.edu_sharing.repository.server.jobs.quartz;

import com.google.gson.Gson;
import org.alfresco.repo.security.authentication.AuthenticationUtil;
import org.alfresco.service.ServiceRegistry;
import org.alfresco.service.cmr.repository.NodeRef;
import org.alfresco.service.cmr.repository.NodeService;
import org.alfresco.service.cmr.security.PermissionService;
import org.alfresco.service.cmr.security.PersonService;
import org.alfresco.service.namespace.QName;
import org.apache.log4j.Logger;
import org.edu_sharing.alfrescocontext.gate.AlfAppContextGate;
import org.edu_sharing.repository.client.tools.CCConstants;
import org.edu_sharing.repository.server.jobs.helper.NodeRunner;
import org.edu_sharing.repository.server.jobs.quartz.annotation.JobDescription;
import org.edu_sharing.repository.server.jobs.quartz.annotation.JobFieldDescription;
import org.edu_sharing.service.authority.AuthorityService;
import org.edu_sharing.service.authority.AuthorityServiceFactory;
import org.edu_sharing.service.nodeservice.NodeServiceFactory;
import org.edu_sharing.service.nodeservice.NodeServiceHelper;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;
import org.springframework.context.ApplicationContext;

import java.io.*;
import java.util.*;
import java.util.stream.Collectors;

@JobDescription(description = "Serialize all metadata of nodes and persistent them as a file")
public class SerializeMetadataJob extends AbstractJob{
	protected Logger logger = Logger.getLogger(SerializeMetadataJob.class);
	@JobFieldDescription(description = "target output filename, when empty will be generated by current timestamp")
	private String filename;
	@JobFieldDescription(description = "folder id to start from")
	private String startFolder;
	@Override
	public void execute(JobExecutionContext context) throws JobExecutionException {

		ApplicationContext applicationContext = AlfAppContextGate.getApplicationContext();

		ServiceRegistry serviceRegistry = (ServiceRegistry) applicationContext.getBean(ServiceRegistry.SERVICE_REGISTRY);
		NodeRunner runner = new NodeRunner();
		runner.setRunAsSystem(true);
		runner.setTransaction(NodeRunner.TransactionMode.Local);
		runner.setThreaded(false);
		String TMP_DIR = System.getProperty("java.io.tmpdir");
		if(filename==null || filename.isEmpty()) {
			filename = "metadata_export_" + System.currentTimeMillis() + ".json";
		}
		if(startFolder != null) {
			runner.setStartFolder(startFolder);
		}
		File file = new File(TMP_DIR, filename);
		try(OutputStreamWriter oos = new OutputStreamWriter(new FileOutputStream(file))) {
			List<AlfrescoNodeModel> nodes = new ArrayList<>();
			runner.setTask((nodeRef) -> {
				if(isInterrupted()) {
					return;
				}
				try {
					AlfrescoNodeModel model = new AlfrescoNodeModel();
					model.type = serviceRegistry.getNodeService().getType(nodeRef).toString();
					model.aspects = serviceRegistry.getNodeService().getAspects(nodeRef).stream().map(QName::toString).collect(Collectors.toSet());
					Map<QName, Serializable> props = serviceRegistry.getNodeService().getProperties(nodeRef);
					Map<String, Serializable> map = new HashMap<>();
					props.forEach((key, value) -> map.put(key.toString(), value));
					model.properties = map;
					//oos.writeObject(model);
					nodes.add(model);
					logger.info("Wrote node " + nodeRef);
				} catch (Throwable e) {
					logger.warn(e.getMessage(), e);
				}
			});
			runner.run();
			oos.write(new Gson().toJson(nodes));
			logger.info("Wrote data to " +file);
		} catch(Exception e) {
			logger.error(e.getMessage(), e);
		}
	}
	public static class AlfrescoNodeModel implements Serializable {
		public String type;
		public Set<String> aspects;
		public Map<String, Serializable> properties;
	}

}
